"""Phase 10A.12: New Executable Alpha Discovery.

Domain enums, types, and closed-family registry definitions.
"""

from enum import Enum


class CandidateID(str, Enum):
    """Preregistered 10 candidate mechanisms for Phase 10A.12."""
    C1_OFA_BURST = "C1_OFA_BURST"                                  # Order-flow acceleration & trade bursts
    C2_CANCEL_RATIO_FLIP = "C2_CANCEL_RATIO_FLIP"                  # Quote cancellation-to-trade shift
    C3_SPREAD_COMPRESSION_BREAKOUT = "C3_SPREAD_COMPRESSION_BREAKOUT"# Compressed spread breakout
    C4_NON_SWEEP_ABSORPTION = "C4_NON_SWEEP_ABSORPTION"            # Hidden liquidity absorption
    C5_VOLATILITY_SPIKE_REBALANCE = "C5_VOLATILITY_SPIKE_REBALANCE"# Volatility-conditioned quote recalibration
    C6_ASYMMETRIC_CROSS_IMPACT = "C6_ASYMMETRIC_CROSS_IMPACT"      # Parent-satellite cross-impact
    C7_REPLENISHMENT_ASYMMETRY = "C7_REPLENISHMENT_ASYMMETRY"      # Asymmetric post-trade depth recovery
    C8_DEPTH_CONCENTRATION_TRANSITION = "C8_DEPTH_CONCENTRATION_TRANSITION" # Depth migration outer-to-inner
    C9_REVERSAL_OF_EXHAUSTION = "C9_REVERSAL_OF_EXHAUSTION"        # Low-volume tick rejection at extremes
    C10_TRADE_SIZE_DISPARITY = "C10_TRADE_SIZE_DISPARITY"          # Institutional block vs retail flow divergence


class CandidateStatus(str, Enum):
    """Lifecycle status of discovery candidates."""
    PREREGISTERED = "PREREGISTERED"
    REJECTED_DISCOVERY_NEGATIVE_EV = "REJECTED_DISCOVERY_NEGATIVE_EV"
    REJECTED_COST_DOMINATION = "REJECTED_COST_DOMINATION"
    REJECTED_SPARSE_DATA = "REJECTED_SPARSE_DATA"
    REJECTED_FALSIFICATION_FAILED = "REJECTED_FALSIFICATION_FAILED"
    VALIDATED_DISCOVERY = "VALIDATED_DISCOVERY"
    SURVIVED_OOS = "SURVIVED_OOS"


class DiscoveryVerdict(str, Enum):
    """Official preregistered verdicts for Phase 10A.12."""
    NEW_EXECUTABLE_EDGE_SUPPORTED = "NEW_EXECUTABLE_EDGE_SUPPORTED"
    PROMISING_BUT_INSUFFICIENT_EVIDENCE = "PROMISING_BUT_INSUFFICIENT_EVIDENCE"
    EXECUTION_EDGE_ABSENT = "EXECUTION_EDGE_ABSENT"
    ARTIFACT = "ARTIFACT"
    INVALIDATED = "INVALIDATED"
    NO_CANDIDATE_SURVIVED = "NO_CANDIDATE_SURVIVED"


class ClosedFamily(str, Enum):
    """Permanently excluded closed alpha families."""
    M1_POST_SWEEP_RESILIENCY = "M1_POST_SWEEP_RESILIENCY"
    M2_STRUCTURAL_SUBPENNY_WEDGE = "M2_STRUCTURAL_SUBPENNY_WEDGE"
    M3_MULTI_OUTCOME_OVERHANG = "M3_MULTI_OUTCOME_OVERHANG"
    PHASE3_9_SEMANTIC_STATARB = "PHASE3_9_SEMANTIC_STATARB"
    PHASE10A6_CROSS_VENUE_ARB = "PHASE10A6_CROSS_VENUE_ARB"
    PHASE10A7_DIRECTIONAL_MICROSTRUCTURE = "PHASE10A7_DIRECTIONAL_MICROSTRUCTURE"
    PHASE10A8_PASSIVE_MARKET_MAKING = "PHASE10A8_PASSIVE_MARKET_MAKING"
    PHASE10A9_HEDGED_PASSIVE = "PHASE10A9_HEDGED_PASSIVE"
    PHASE10A10_DETERMINISTIC_RESOLUTION_LAG = "PHASE10A10_DETERMINISTIC_RESOLUTION_LAG"
    STATIC_DEPTH_IMBALANCE = "STATIC_DEPTH_IMBALANCE"
    SIMPLE_STALE_QUOTE = "SIMPLE_STALE_QUOTE"
    SIMPLE_SUM_TO_ONE = "SIMPLE_SUM_TO_ONE"


CLOSED_FAMILY_VERDICTS = {
    ClosedFamily.M1_POST_SWEEP_RESILIENCY: "M1_INVALIDATED",
    ClosedFamily.M2_STRUCTURAL_SUBPENNY_WEDGE: "EXECUTION_EDGE_ABSENT",
    ClosedFamily.M3_MULTI_OUTCOME_OVERHANG: "M3_EXECUTION_EDGE_ABSENT",
    ClosedFamily.PHASE3_9_SEMANTIC_STATARB: "INVALIDATED_NON_CAUSAL",
    ClosedFamily.PHASE10A6_CROSS_VENUE_ARB: "CLOSED_NO_CROSSED_BOOK",
    ClosedFamily.PHASE10A7_DIRECTIONAL_MICROSTRUCTURE: "CLOSED_HEURISTIC_FAILURE",
    ClosedFamily.PHASE10A8_PASSIVE_MARKET_MAKING: "CLOSED_ADVERSE_SELECTION",
    ClosedFamily.PHASE10A9_HEDGED_PASSIVE: "CLOSED_LEG_RISK",
    ClosedFamily.PHASE10A10_DETERMINISTIC_RESOLUTION_LAG: "CLOSED_GENUINELY_SPARSE",
    ClosedFamily.STATIC_DEPTH_IMBALANCE: "CLOSED_NO_DIRECTIONAL_EDGE",
    ClosedFamily.SIMPLE_STALE_QUOTE: "CLOSED_LATENCY_ARBITRAGED",
    ClosedFamily.SIMPLE_SUM_TO_ONE: "CLOSED_SPREAD_DOMINATED",
}
