"""Phase 10A.10-C Forensic Audit of Phase 10A.10-B Resolution Lag Result."""

from enum import Enum


class Phase10A10CVerdict(Enum):
    RESULT_VERIFIED = "RESULT_VERIFIED"
    RESULT_VERIFIED_WITH_REPORTING_ERRORS = "RESULT_VERIFIED_WITH_REPORTING_ERRORS"
    RESULT_INVALID_EXECUTION_MODEL = "RESULT_INVALID_EXECUTION_MODEL"
    RESULT_INVALID_OUTCOME_MAPPING = "RESULT_INVALID_OUTCOME_MAPPING"
    RESULT_INVALID_TIMESTAMP_MODEL = "RESULT_INVALID_TIMESTAMP_MODEL"
    RESULT_INVALID_STATISTICS = "RESULT_INVALID_STATISTICS"
    RESULT_DUPLICATION_ARTIFACT = "RESULT_DUPLICATION_ARTIFACT"
    RESULT_SYNTHETIC_CONTAMINATION = "RESULT_SYNTHETIC_CONTAMINATION"
    RESULT_LEAKAGE_DETECTED = "RESULT_LEAKAGE_DETECTED"
    RESULT_NOT_REPRODUCIBLE = "RESULT_NOT_REPRODUCIBLE"
