"""Cross-Venue Polymarket-Kalshi Arbitrage Framework (Phase 10A.6e & 10A.6g)."""

from src.cross_venue.schema import (
    EquivalenceClass,
    MappingStatus,
    StaleStatus,
    CategoryStatus,
    FinalArbitrageVerdict,
    CanonicalEconomicContract,
    ContractMappingResult,
    SyncQuote,
    QuoteState,
    CrossVenueCostBreakdown,
    ArbitrageLeg,
    LegRiskResult,
    CapitalCapacityResult,
    CrossVenueArbitrageOpportunity,
)
from src.cross_venue.settlement_normalizer import SettlementNormalizer
from src.cross_venue.synchronizer import CrossVenueSynchronizer
from src.cross_venue.cross_venue_arb_engine import CrossVenueArbEngine
from src.cross_venue.db_store import CrossVenueDBStore
from src.cross_venue.cross_venue_adversarial import (
    AdversarialConfig,
    BaselineExecutionResult,
    LatencyStressResult,
    DepthStressResult,
    FeeStressResult,
    SlippageStressResult,
    QuoteStalenessResult,
    AsynchronousLegResult,
    PriceMovementResult,
    CapitalStressResult,
    CorrelatedStressResult,
    EdgeSurvivalBound,
    AdversarialAuditSummary,
    CrossVenueAdversarialEngine,
)

__all__ = [
    "EquivalenceClass",
    "MappingStatus",
    "StaleStatus",
    "CategoryStatus",
    "FinalArbitrageVerdict",
    "CanonicalEconomicContract",
    "ContractMappingResult",
    "SyncQuote",
    "QuoteState",
    "CrossVenueCostBreakdown",
    "ArbitrageLeg",
    "LegRiskResult",
    "CapitalCapacityResult",
    "CrossVenueArbitrageOpportunity",
    "SettlementNormalizer",
    "CrossVenueSynchronizer",
    "CrossVenueArbEngine",
    "CrossVenueDBStore",
    "AdversarialConfig",
    "BaselineExecutionResult",
    "LatencyStressResult",
    "DepthStressResult",
    "FeeStressResult",
    "SlippageStressResult",
    "QuoteStalenessResult",
    "AsynchronousLegResult",
    "PriceMovementResult",
    "CapitalStressResult",
    "CorrelatedStressResult",
    "EdgeSurvivalBound",
    "AdversarialAuditSummary",
    "CrossVenueAdversarialEngine",
]
